name: DLP Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run DLP Script
      run: |
        chmod +x scripts/dlp-check.sh
        ./scripts/dlp-check.sh
